language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "iojs"

env:
  - CC=gcc-4.8 CXX=g++-4.8
  - CC=clang-3.6 CXX=clang++-3.6 npm_config_clang=1

before_install:
  npm install -g npm@'>=2.13.2'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6

matrix:
  allow_failures:
    - env: CC=clang-3.6 CXX=clang++-3.6
      node_js: "0.10"
    - env: CC=clang-3.6 CXX=clang++-3.6
      node_js: "0.12"
