language: node_js

os:
  - linux
  - osx

node_js:
  - "6.0"
  - "5.11"
  - "4.4"
  - "0.12"
  - "0.10"

env:
  - CC=clang CXX=clang
  - CC=gcc-4.8 CXX=g++-4.8
#  - CC=clang-3.8 CXX=clang++-3.8 npm_config_clang=1

matrix:
  exclude:
    - os: linux
      env: CC=clang CXX=clang
    - os: osx
      env: CC=gcc-4.8 CXX=g++-4.8
#    - os: osx
#      env: CC=clang-3.8 CXX=clang++-3.8 npm_config_clang=1

before_install:
  VER=`npm --version` eval 'ARRAY=(${VER//./ }) && if [ ${ARRAY[0]} -lt 2 ] || ( [ ${ARRAY[0]} -eq 2 ] && [ ${ARRAY[1]} -lt 13 ] ) ; then npm install -g npm; fi'

after_script:
  if [ ${TRAVIS_JOB_NUMBER##*.} == 1 ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bin/ci-trigger; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.8
    packages:
      - gcc-4.8
      - g++-4.8
#      - clang-3.8
