version: 0.0.{build}
skip_tags: true
os: Visual Studio 2015
shallow_clone: true
init:
- ps: Install-Product node $env:nodejs_version
environment:
  matrix:
# Pending a fix for https://github.com/nodejs/nan/issues/462
#  - nodejs_version: 0.10
  - nodejs_version: 0.12
# Pending a fix for https://github.com/nodejs/node-gyp/issues/724
#  - nodejs_version: 4
install:
- npm install -g npm
- set PATH=%APPDATA%\npm;%PATH%
- npm install
build: off
test_script:
- node --version
- npm --version
- npm test
